name: contribution-snake

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Job to update Snake
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: allanavelar/github-readme-snake@master
        id: snake-svg
        with:
          github_user_name: allanavelar
          svg_out_path: dist/github-contribution-grid-snake.svg
          drawOpts: "{\"colorSnake\":\"#fdbe04\",\"dark\":{\"colorEmpty\":\"#01242B\",\"colorDots\":{\"1\":\"#014451\",\"2\":\"#016173\",\"3\":\"#01A1BF\",\"4\":\"#02D1F7\"}}}"

      - uses: avnsystems/action-github-pages@v2.5.0
        with:
          target_branch: readme-snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
